name: yomou
description: "Yomou - a Kotatsu-style manga reader."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.11.0
  html: ^0.15.6
  http: ^1.6.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  image: ^4.3.0
  path_provider: ^2.1.6
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0 # Moved here and indented correctly
  path: ^1.9.1
  flutter_inappwebview: ^6.0.0
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  remixicon: ^4.9.3
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  flutter_local_notifications: ^22.3.1
  workmanager: ^0.10.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "logo_light.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "logo_light.png"
